kmu-crc/osd_front

src/config.js
src/modules/socket/index.js

Issue test

---

src/components/Registration/SignUpForm/SignUpForm.js

Revert "회원가입 규칙"

---

src/components/Designs/CardSourceDetail/CardSourceDetail.js
src/components/Designs/Design/Design.js

add designcard info #77 
playing video immediately #78

Issue 077 & Issue 078

---

src/components/Registration/SignUpForm/SignUpForm.js

비밀번호 확인 수정

---

src/components/Users/ModifyMyDetail/ModifyMyDetail.js

issue-004 자기소개 문자수 제한

---

src/components/Users/ModifyMyDetail/ModifyMyDetail.js

issue-005 이름 문자수 제한

---

src/components/Designs/CreateDesignForm/CreateDesignForm.js
src/components/Users/ModifyMyDetail/ModifyMyDetail.js

Issue-012 제목 글자수 제한

---

src/components/Designs/CreateDesignForm/CreateDesignForm.js
src/components/Users/ModifyMyDetail/ModifyMyDetail.js

디자인 등록 작품설명 글자수 1000자로 제한 완료하였습니다.

Issue-013 작품설명 글자수 제한

---

src/components/Messages/MessageList/MessageList.js

메세지창 개수 변경

---

src/components/Designs/DesignBoardCard/CardTitleUpdate.js

Issue-010 디자인 목록 디자인 이름

---

src/components/Designs/Design/Design.js

category position to left.
update position to right.

modify category position kmu-crc#77

---

src/components/Designs/ModifyDesignInfo/ModifyDesignInfo.js

디자인 수정부분 설명 글자수 1000자로 제한하였습니다.

Issue-061 디자인 수정 설명 글자수 제한

---

src/components/Designs/ModifyDesignInfo/ModifyDesignInfo.js

Issue-060 디자인 수정 제목 글자수 제한

---

src/components/Designs/DesignBoardCard/CardContentUpdate.js

issue-029 디자인 상세보기 설명 글자수 제한

---

src/modules/DateFormat/DateFormat.js

issue #99 일자형식

---

src/components/Commons/FormItems/AsyncInput.js
src/modules/Validates/Validates.js

input length=2 & rewrite placeholder

---

src/StyleGuide.js
src/components/Designs/DesignDetail/DesignComment.js

댓글오브댓글!
...
코드 엄청 더러움.. 이거 다음버젼에서 제대로 고치겠음. 하ㅏㅏㅏㅏㅏ

#087 comment of comments

---

src/components/Designs/CreateCard/CreateCard.js

컨텐츠 제목 20자 수정

---

src/components/Registration/SignUpForm/SignUpForm.js

use agreement fix

---

src/components/Commons/Header/Alram.js
src/components/Designers/Designer/Designer.js
src/components/Designers/DesignerDetail/DesignerDetail.js
src/components/Designers/DesignerList/DesignerList.js
src/components/Designs/Design/Design.js
src/components/Designs/DesignBoardCard/DesignBoardCard.js
src/components/Designs/DesignDetail/DesignDetail.js
src/components/Designs/DesignList/DesignList.js
src/components/Designs/DesignStepCard/DesignStepCard.js
src/components/Groups/Group/Group.js
src/components/Groups/GroupList/GroupList.js
src/containers/Groups/DesignInGroupContainer/DesignInGroupContainer.js
src/containers/Groups/GroupInGroupContainer/GroupInGroupContainer.js

숫자 출력 형식 변경
ex)
999 -> 999
1000 -> 1k
1100 -> 1.1k
1000000 -> 1m
1100000 -> 1.1m

number format changed, no-named issue

---

package.json
src/StyleGuide.js
src/components/Commons/FormItem/FormItem.js
src/components/Designs/DesignDetail/DesignComment.js
src/components/Designs/DesignDetail/DesignDetail.js
src/components/TestForm/TestForm.js

#87 replies of comment

---

src/actions/Designs/JoinDesign.js
src/components/Commons/Header/Alram.js
src/components/Designs/ModifyDesignMember/ModifyDesignMember.js
src/containers/MyPage/MyInvitedContainer/MyInvitedContainer.js

꼬인브런치 풀고 해당이슈에 속하는 커밋만 풀리퀘합니다. 확인후머지해주세요 :)
kmu-crc/osd_front#185

#185 alarm request parameter modified - boolean to string

---

src/actions/Designs/JoinDesign.js
src/components/Commons/Header/Alram.js
src/components/Designs/ModifyDesignMember/ModifyDesignMember.js
src/containers/MyPage/MyInvitedContainer/MyInvitedContainer.js

kmu-crc/osd_front#143 > kmu-crc/osd_front#189

alarm pull request

---

src/components/Commons/FormItems/AsyncInput.js
src/components/Commons/FormItems/FormInput.js
src/components/Registration/SignUpForm/SignUpModal.js

1자 이상 입력해야지만 검색이 가능하게끔 코드를 수정했습니다.
SearchList함수 내에 조건문을 추가하였고,
입력 minLength = 1로 조건을 넣었습니다.

change the search condition kmu-crc#158

---

src/modules/Validates/Validates.js

validates에 >=2 을 1로 변경하여 1자만 입력하여도 검색이 되게끔 변경하였습니다.

change the minlength from 2 to 1

---

src/components/Registration/SignInForm/SignInForm.js

로그인 시, 사용자가 직전에 있던 페이지로 이동하게끔 변경하였습니다.

go to prior page when signin kmu-crc#172

---

src/App.js
src/components/Designs/ModifyDesign/ModifyDesign.js
src/components/Designs/ModifyDesignInfo/ModifyDesignInfo.js
src/containers/Designs/ModifyDesignFormContainer/ModifyDesignFormContainer.js

#196 디자인 작성자가 아니면 뒤로가게 코드 추가하였습니다.

check permission

---

src/components/Designs/DesignDetail/DesignComment.js

#201 design comment of comment update time

---

src/components/Users/MyDetail/MyDetail.js

number format in my detail page

---

src/components/Commons/ScrollList/ScrollList.js
src/components/Designers/Designer/Designer.js
src/components/Designers/DesignerList/DesignerList.js
src/containers/Designer/ScrollDesignerListContainer/ScrollDesignerListContainer.js

#203 디자이너목록에서 자신의 카드 클릭하면 바로 [마이페이지]로 이동합니다.

redirect designer to mypage if clicked designer is my profile

---

src/components/Designs/DesignDetail/DesignDetail.js
src/containers/Designs/CreateDesignFormContainer/CreateDesignFormContainer.js

ISSUE #194 - check designer is

---

src/components/Commons/Footer/Footer.js
src/components/Commons/Header/Alram.js
src/components/Designers/Designer/Designer.js
src/components/Designers/DesignerDetail/DesignerDetail.js
src/components/Designs/Design/Design.js
src/components/Designs/DesignBoard/DesignBoard.js
src/components/Designs/DesignBoardCard/DesignBoardCard.js
src/components/Designs/DesignDetail/DesignDetail.js
src/components/Groups/Group/Group.js
src/components/Groups/GroupDetail/GroupDetail.js
src/components/Groups/GroupDetailNew/GroupDetailNew.js
src/components/Messages/MessageDetail/MessageDetail.js
src/components/Messages/MessageList/MessageList.js
src/components/Users/MyDetail/MyDetail.js
src/modules/TextFormat/TextFormat.js
src/modules/TextFormat/index.js

text_overflow componen

---

src/components/Commons/Footer/Footer.js
src/components/Commons/Header/Alram.js
src/components/Designers/Designer/Designer.js
src/components/Designers/DesignerDetail/DesignerDetail.js
src/components/Designs/Design/Design.js
src/components/Designs/DesignBoard/DesignBoard.js
src/components/Designs/DesignBoardCard/DesignBoardCard.js
src/components/Designs/DesignDetail/DesignDetail.js
src/components/Groups/Group/Group.js
src/components/Groups/GroupDetail/GroupDetail.js
src/components/Groups/GroupDetailNew/GroupDetailNew.js
src/components/Messages/MessageDetail/MessageDetail.js
src/components/Messages/MessageList/MessageList.js
src/components/Users/MyDetail/MyDetail.js
src/modules/TextFormat/TextFormat.js
src/modules/TextFormat/index.js

#200 이슈에 해당되는 커밋입니다. 개선된 부분이 있으니 확인부탁드립니다!!!

#200 이슈 개선커밋

---

src/components/Designs/DetailView/DetailView.js
src/containers/Designs/DesignDetailViewContainer/DesignDetailViewContainer.js

#228 update design time in blog mode

---

src/components/Designs/CardSourceDetail/CardSourceDetail.js

TEXT also possible right now

---

src/components/Commons/FormItems/FormThumbnail.js
src/components/Commons/FormItems/MultiUpload.js
src/modules/Validates/Validates2.js

bmp file is possible to set thumbnail

---

src/components/Designs/ModifyDesign/ModifyDesign.js
src/components/Groups/GroupDetailNew/GroupDetailNew.js
src/containers/Designs/ModifyDesignFormContainer/ModifyDesignFormContainer.js
src/containers/Groups/EditDesignListContainer/EditDesignListContainer.js
src/containers/Groups/EditGroupListContainer/EditGroupListContainer.js
src/containers/Groups/ModifyGroupInfoContainer/ModifyGroupInfoContainer.js

group modify permission and manage group without btn

---

src/components/Commons/ValidateForm/ValidateForm.js
src/components/Groups/JoinGroup/MyDesignList.js

select all designs when request to join in group #176

---

src/actions/Authentication/index.js
src/containers/Commons/RequiresAuth/RequiresAuth.js

comment out not need code to maintain token

---

src/components/Commons/FormItems/FormThumbnail.js
src/components/Users/ModifyMyDetail/ModifyMyDetail.js

password can change after click change password button

---

src/components/Registration/SignUpForm/SignUpForm.js
src/components/Users/ModifyMyDetail/ModifyMyDetail.js
src/modules/Validates/Validates2.js

validate nickname character with validate2 js file

---

src/actions/Categorys/Categorys.js
src/actions/Commons/Notification.js
src/components/Commons/Header/Header.js
src/components/Designs/Design/Design.js
src/containers/Commons/HeaderContainer/HeaderContainer.js
src/modules/Sessions/Sessions.js

#88 노티피케이션 기능 추가
- 백엔드로부터 노티가져옴
- 가져온 노티 중 쿠키에 있으면 출력하지 않음
- 출력된 노티화면에서 체크박스 체크하면 해당 노티 쿠키에 저장(이후표시안함)

Issue#88 manager reponse branch

---

src/components/Designers/DesignerDetailHeader/DesignerDetailHeader.js
src/components/Messages/MessageList/MessageList.js
src/components/MypageHeader/MypageHeader.js
src/components/Registration/SignUp/SignUp.js
src/containers/Designer/DesignerDetailContainer/DesignerDetailContainer.js

마이페이지 디자이너 페이지 ui일치,
내 디자이너페이지를 조회할경우 예외처리

마이페이지와 디자이너 정보페이지 수정,

---

src/components/Commons/FileIcon/FileIcon.js
src/components/Designs/ModifyDesign/ModifyDesign.js
src/components/Header/Footer/Footer.js
src/components/Header/SignNav/SignInModal.js
src/opendesign_style.js

0925회의 수정사항 수정

---

src/components/Commons/Loading/Loading.js
src/components/Designers/DesignerDetailHeader/DesignerDetailHeader.js
src/components/Designs/CardSourceDetail/CardSourceDetail.js
src/components/Designs/DesignInfo/DesignInfo.js
src/components/Designs/GridEditor/NewCardModal.js
src/components/Groups/GroupInfo/GroupInfo.js
src/components/Messages/MessageDetail/MessageDetail.js
src/components/Messages/MessageList/MessageList.js
src/containers/Designs/ModifyDesignInfoContainer/ModifyDesignInfoContainer.js
src/pages/ModifyDesignPage/ModifyDesignPage.js

issue commits

---

src/components/Commons/Comment/Comment.js
src/components/Designs/DesignInfo/DesignInfo.js
src/components/Designs/ModifyDesign/ModifyDesign.js
src/components/MypageBody/MypageBody.js
src/components/Users/ModifyMyDetail/ModifyMyDetail.js
src/components/Users/ModifyMyDetail/ModifyMyDetail/SectionAdditional/SectionAdditional.js
src/components/Users/ModifyMyDetail/ModifyMyDetail/SectionBuziness/SectionBuziness.js
src/containers/Designs/ModifyDesignInfoContainer/ModifyDesignInfoContainer.js
src/redux/modules/personal.js

css commits,
permission check bug fix commit

191010 commits

---

src/components/Commons/CheckBox/CheckBox.js
src/components/Commons/FormItem/FormItem.js
src/components/Designers/CreateDesigner/CreateDesigner.js
src/components/Designers/CreateDesigner/ModifyMyDetail/SectionAdditional/SectionAdditional.js
src/components/Designers/CreateDesigner/ModifyMyDetail/SectionBuziness/SectionBuziness.js
src/components/Designers/DesignerDetailBody/DesignerDetailBody.js
src/components/Designs/CardSourceDetail/CardSourceDetail.js
src/components/Designs/CreateDesign/CreateDesign.js
src/components/Designs/DesignInfo/DesignInfo.js
src/components/Designs/GridEditor/GridTools.js
src/components/Designs/ModifyDesign/ModifyDesign.js
src/components/MypageBody/MypageBody.js
src/components/Registration/SignUp/SignUp.js
src/components/Registration/UserDetailFrom/ModifyMyDetail/SectionBuziness/SectionBuziness.js
src/components/Users/ModifyMyDetail/ModifyMyDetail/SectionBuziness/SectionBuziness.js
src/containers/Designer/DesignerDetailContainer/DesignerDetailContainer.js
src/containers/MyPage/MyDetailContainer/MyDetailContainer.js
src/redux/modules/designer/designer.js

- checkbox make as redbox
- designer detail copy to mypage detail almost not exactly same but many things same, so! I used it not C+V
- card background transparent value adjustment
- bugfix
- tab priority code modified.

kaizen commits

---

src/components/Designs/GridEditor/GridEditor.js
src/components/Groups/GroupInfo/GroupInfo.js

- grid-editor bugfix
- group-detail
- design-detail(2/2)

responsive web page

---

src/Admin/AdminPage/RequestManagerPage.js
src/Admin/components/RequestManager/RequestManager.js
src/Admin/components/RequestManager/index.js

market admin

---

src/components/GridEditor/GridEditor.js
src/components/Items/ItemDetail/CardSourceDetail.js
src/components/Items/ItemDetail/ItemDetail.js
src/components/Items/ItemPurchase/ItemPurchase.js
src/components/Items/ModifyItemInfo/ModifyItemInfo.js
src/components/Request/DesignerRequestBoard/DesignerRequestBoard.js
src/components/Users/MyDetail/MyDetail.js
src/containers/Items/ItemStepContainer/ItemStepContainer.js
src/containers/Payment/PaymentContainer.js
src/containers/Products/ProductDetailContainer/ProductDetailContainer.js
src/containers/Products/ProductPurchaseContainer/ProductPurchaseContainer.js

commit for db column changed, mypage counter
